### ISSUE TITLE
Update pulumi script(s)

### ISSUE THREAD

**Issue by rchan26** [alan-turing-institute/reginald#113]
- [x] Full slack bot
- [x] Slack bot
- [x] Optional: VM for LLM

**Comment by rwood-97** [comment]
Pulumi scripts now work for both full slack bot and api bot. See #132 

I've broken something in the `hack_week` set up so we might need to delete and recreate in order to regain access but have asked for help in a relevant issue on the pulumi repo so hopefully I can fix this. 

Things we still want to deal with are:
- Better error handling in the api bot if the VM is off, this should return an 'out of office' message but at the moment just hangs and you need to restart the container.
- Reggie (handbook) is broken at the moment but we just need to get the app/bot tokens again and should be fixed

**Comment by rchan26** [comment]
Did in #196
